[env:base]
platform = ststm32
board = black_f407zg
framework = stm32cube
build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -DUSE_HAL_DRIVER
    -DSTM32F4
    -DSTM32F407xx
    -DSTM32F40_41xxx
    -DHSE_VALUE=8000000
; STM32 ROM bootloader upload through a 3.3 V USB-to-TTL adapter.
upload_protocol = serial
upload_speed = 115200
upload_port = COM3
extra_scripts = post:$PROJECT_DIR/../tools/stm32_serial_offset.py
build_type = release

[env:app_a]
extends = env:base
board_build.ldscript = $PROJECT_DIR/STM32F407ZGTx_APP.ld
board_upload.offset_address = 0x08020000
custom_upload_length = 393216
build_flags = ${env:base.build_flags}
    -DAPP_BASE_ADDR=0x08020000
    -I $PROJECT_DIR/../src
    -I $PROJECT_DIR/../src/drivers
    -I $PROJECT_DIR/../include

[env:app_b]
extends = env:base
board_build.ldscript = $PROJECT_DIR/STM32F407ZGTx_APP_B.ld
board_upload.offset_address = 0x08080000
custom_upload_length = 393216
build_flags = ${env:base.build_flags}
    -DAPP_BASE_ADDR=0x08080000
    -I $PROJECT_DIR/../src
    -I $PROJECT_DIR/../src/drivers
    -I $PROJECT_DIR/../include
