#!/usr/bin/env python3
"""
FlashSafe Pro - Key Pair Generator

Generates a secp256r1 (NIST P-256) key pair for firmware signing:
  private_key.pem  -> server side, keep secret, NEVER ship
  public_key.h     -> embed in the bootloader (include/public_key.h)

Usage:
  python tools/gen_keypair.py -o tools/keys
  copy tools/keys/public_key.h include/public_key.h
  rebuild bootloader

The key material is deterministic RFC 6979; signatures produced by
tools/pack_firmware.py are low-S.
"""

import os
import sys
import argparse
import hashlib
import base64


def format_c_array(name, data, per_line=16):
    """Format bytes as a C static const uint8_t array."""
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
        lines.append("    " + chunk + ",")
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + \
           "\n".join(lines) + "\n};"


def generate_keypair(output_dir):
    """Generate ECDSA secp256r1 key pair."""
    try:
        from ecdsa import SigningKey, NIST256p
    except ImportError:
        print("Error: ecdsa library not installed. Install with: pip install ecdsa")
        sys.exit(1)

    sk = SigningKey.generate(curve=NIST256p)
    vk = sk.get_verifying_key()

    raw = vk.to_string()          # 64 bytes: x || y
    x_bytes, y_bytes = raw[:32], raw[32:]
    pubkey_hash = hashlib.sha256(raw).digest()

    os.makedirs(output_dir, exist_ok=True)

    private_pem_path = os.path.join(output_dir, "private_key.pem")
    der = sk.to_der()
    b64 = base64.encodebytes(der).decode('ascii').replace('\n', '')
    lines = [b64[i:i + 64] for i in range(0, len(b64), 64)]
    with open(private_pem_path, 'w', encoding='utf-8') as f:
        f.write("-----BEGIN EC PRIVATE KEY-----\n")
        for line in lines:
            f.write(line + "\n")
        f.write("-----END EC PRIVATE KEY-----\n")
    print(f"Private key saved to: {private_pem_path}")

    public_h_path = os.path.join(output_dir, "public_key.h")
    with open(public_h_path, 'w', encoding='utf-8') as f:
        f.write("/* Auto-generated by tools/gen_keypair.py - DO NOT EDIT */\n")
        f.write("/*\n")
        f.write(" * !!! DEVELOPMENT KEY - not for production !!!\n")
        f.write(" * Regenerate before shipping:\n")
        f.write(" *   python tools/gen_keypair.py -o tools/keys\n")
        f.write(" *   copy tools/keys/public_key.h include/public_key.h\n")
        f.write(" *   rebuild bootloader\n")
        f.write(" */\n")
        f.write("#ifndef __PUBLIC_KEY_H\n")
        f.write("#define __PUBLIC_KEY_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("/* Public key (X || Y) - 64 bytes, secp256r1 */\n")
        f.write(format_c_array("PUBLIC_KEY", raw) + "\n\n")
        f.write("/* SHA-256 of the public key */\n")
        f.write(format_c_array("PUBLIC_KEY_HASH", pubkey_hash) + "\n\n")
        f.write("#endif /* __PUBLIC_KEY_H */\n")
    print(f"Public key header saved to: {public_h_path}")
    print(f"\nPublic key SHA-256: {pubkey_hash.hex()}")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Generate ECDSA secp256r1 key pair for FlashSafe Pro")
    parser.add_argument("--output-dir", "-o", default="./keys",
                        help="Output directory (default: ./keys)")
    args = parser.parse_args()

    if not generate_keypair(args.output_dir):
        sys.exit(1)

    print("\nKey pair generation complete!")


if __name__ == "__main__":
    main()
