#!/usr/bin/env python3
"""Build, sign, verify, and describe a matching FlashSafe A/B release."""

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys


PROJECT_ROOT = Path(__file__).resolve().parent.parent
TOOLS_DIR = PROJECT_ROOT / "tools"
APP_DIR = PROJECT_ROOT / "app"
FIRMWARE_DIR = PROJECT_ROOT / "firmware"
APP_VERSION_HEADER = APP_DIR / "include" / "app_version.h"
PRIVATE_KEY = TOOLS_DIR / "keys" / "private_key.pem"
PUBLIC_KEY = PROJECT_ROOT / "include" / "public_key.h"


def validate_version(version):
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise ValueError("version must use X.Y.Z format")


def write_app_version_header(path, version):
    validate_version(version)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "#ifndef APP_VERSION_H\n"
        "#define APP_VERSION_H\n\n"
        "/* Generated by tools/release_firmware.py. */\n"
        f"#define APP_VERSION_STRING \"{version}\"\n\n"
        "#endif /* APP_VERSION_H */\n",
        encoding="utf-8",
    )


def sha256_file(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(64 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def make_manifest(version, package_specs):
    validate_version(version)
    packages = []
    for spec in package_specs:
        path = Path(spec["path"])
        target_slot = spec["target_slot"].upper()
        if target_slot not in ("A", "B"):
            raise ValueError("target_slot must be A or B")
        if not path.is_file():
            raise FileNotFoundError(path)
        packages.append({
            "name": path.name,
            "target_slot": target_slot,
            "size": path.stat().st_size,
            "sha256": sha256_file(path),
        })
    packages.sort(key=lambda item: item["target_slot"])
    return {"schema": 1, "version": version, "packages": packages}


def platformio_executable():
    found = shutil.which("platformio")
    if found:
        return found
    suffix = "Scripts/platformio.exe" if os.name == "nt" else "bin/platformio"
    fallback = Path.home() / ".platformio" / "penv" / suffix
    if fallback.is_file():
        return str(fallback)
    raise FileNotFoundError("PlatformIO executable not found")


def run(command):
    print("+", " ".join(str(part) for part in command))
    subprocess.run(command, cwd=PROJECT_ROOT, check=True)


def build_and_package(version, output_dir, skip_tests=False):
    validate_version(version)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    write_app_version_header(APP_VERSION_HEADER, version)

    pio = platformio_executable()
    if not skip_tests:
        run([sys.executable, "-m", "unittest", "discover", "-s", "tools/tests",
             "-p", "test_*.py"])

    specs = []
    for environment, slot in (("app_a", "A"), ("app_b", "B")):
        run([pio, "run", "-d", "app", "-e", environment])
        binary = APP_DIR / ".pio" / "build" / environment / "firmware.bin"
        package = output_dir / f"firmware_v{version}_slot{slot}.pkg"
        run([sys.executable, str(TOOLS_DIR / "pack_firmware.py"),
             "--input", str(binary), "--key", str(PRIVATE_KEY),
             "--pubkey", str(PUBLIC_KEY), "--version", version,
             "--output", str(package), "--target-slot", slot])
        run([sys.executable, str(TOOLS_DIR / "verify_pkg.py"),
             "--pkg", str(package), "--pubkey", str(PUBLIC_KEY),
             "--expected-slot", slot])
        specs.append({"path": package, "target_slot": slot})

    manifest = make_manifest(version, specs)
    manifest["generated_utc"] = dt.datetime.now(dt.timezone.utc).replace(
        microsecond=0
    ).isoformat().replace("+00:00", "Z")
    manifest_path = output_dir / f"release-v{version}.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Release manifest: {manifest_path}")
    return manifest_path


def main():
    parser = argparse.ArgumentParser(
        description="Build and verify matching FlashSafe Slot-A and Slot-B packages"
    )
    parser.add_argument("--version", "-v", required=True,
                        help="release version in X.Y.Z format")
    parser.add_argument("--output-dir", "-o", default=str(FIRMWARE_DIR),
                        help="directory for .pkg files and release manifest")
    parser.add_argument("--skip-tests", action="store_true",
                        help="skip host unit tests before release build")
    args = parser.parse_args()
    try:
        build_and_package(args.version, args.output_dir, args.skip_tests)
    except (OSError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"Release failed: {exc}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
