/**
 * ECDSA Public Key - FlashSafe Pro
 *
 * The public key is embedded in the bootloader code (read-only flash)
 * rather than stored in a writable config sector. This prevents an
 * attacker from replacing the key to sign their own firmware.
 *
 * public_key.h is generated by tools/gen_keypair.py. The shipped header
 * contains a DEVELOPMENT key - regenerate for production:
 *
 *   python tools/gen_keypair.py -o tools/keys
 *   copy tools/keys/public_key.h include/public_key.h
 *   rebuild bootloader
 */

#include "pubkey.h"
#include "public_key.h"
#include <stdio.h>

int pubkey_init(void)
{
    printf("[KEY] Embedded public key loaded (P-256)\r\n");
    printf("[KEY] SHA-256: ");
    for (int i = 0; i < 32; i++) {
        printf("%02X", PUBLIC_KEY_HASH[i]);
    }
    printf("\r\n");
    return 0;
}

int pubkey_store(const uint8_t *pubkey, size_t len)
{
    (void)pubkey;
    (void)len;
    printf("[KEY] Embedded public key cannot be replaced at runtime\r\n");
    return -1;
}

const uint8_t *pubkey_get(void)
{
    return PUBLIC_KEY;
}

const uint8_t *pubkey_hash(void)
{
    return PUBLIC_KEY_HASH;
}

bool pubkey_is_loaded(void)
{
    return true;
}
